# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 05:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoinAddress', models.CharField(max_length=64)),
                ('bitcoinBalance', models.DecimalField(decimal_places=8, max_digits=16)),
                ('ethereumAddress', models.CharField(max_length=64)),
                ('ethereumBalance', models.DecimalField(decimal_places=8, max_digits=16)),
                ('pendingTx', models.TextField()),
                ('latestTx', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
