# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtomicExchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='visibility',
            field=models.CharField(default='covert', max_length=30),
        ),
    ]
