# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtomicExchange', '0002_account_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='depositCount',
            field=models.BigIntegerField(default=0),
        ),
    ]
