# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('involvesWatchonly', models.BooleanField()),
                ('account', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=16)),
                ('label', models.TextField()),
                ('confirmations', models.IntegerField()),
                ('blockhash', models.CharField(max_length=64)),
                ('blockindex', models.BigIntegerField()),
                ('blocktime', models.BigIntegerField()),
                ('txid', models.CharField(max_length=64)),
                ('vout', models.BigIntegerField()),
                ('walletconflicts', models.TextField()),
                ('time', models.BigIntegerField()),
                ('timereceived', models.BigIntegerField()),
                ('bip125replaceable', models.CharField(max_length=30)),
            ],
        ),
    ]
