# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0002_auto_20180614_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
