# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AtomicExchange', '0003_account_depositcount'),
        ('bitcoin', '0003_transaction_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='AtomicExchange.Account'),
        ),
    ]
